version: "3.3"
services:
     web:
       image: nginx:latest
       build:
         context: ./src
       container_name: "nginx_lar"
       restart: unless-stopped
       tty: true
       working_dir: /var/www/html
       ports:
         - "8282:80"
       volumes:
         - ./src:/var/www/html
         - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
         - ./docker/nginx/logs:/var/log/nginx
       links:
         - php-fpm
       networks:
         - app-network


     php-fpm:
#       image: php:8-fpm
       build:
         context: ./
         dockerfile: ./docker/php/Dockerfile
       container_name: "php_lar"
       tty: true
       working_dir: /var/www/html
       volumes:
         - ./src:/var/www/html
         - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
       networks:
         - app-network

     db:
       image: mysql:8
       container_name: "db_lar"
       restart: unless-stopped
       tty: true
       ports:
       - "3307:3306"
       environment:
         MYSQL_DATABASE: db_lar
         MYSQL_ROOT_PASSWORD: 123456

       volumes:
        - ./db:/var/lib/mysql
       networks:
         - app-network
networks:
  app-network:
    driver: bridge