version: "3.3"
services:
     web:
       image: nginx:latest
       build:
         context: ./src
       container_name: "nginx_lar"
       restart: unless-stopped
       ports:
         - "8282:80"
       volumes:
         - ./src:/var/www/html
         - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
         - ./docker/nginx/logs:/var/log/nginx
       links:
         - php-fpm

     php-fpm:
       image: php:8-fpm
       container_name: "php_lar"
       volumes:
         - ./src:/var/www/html
